export const SET_PERMISSION_STATE = 'SET_PERMISSION_STATE';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_NEARBY_DATA = 'SET_NEARBY_DATA';
export const SET_FEATURED_DATA = 'SET_FEATURED_DATA';
export const SET_SAVED_DATA = 'SET_SAVED_DATA';
